### ISSUE TITLE
"Error: Distribution of .aab is not supported for groups/testers"

### ISSUE THREAD

**Issue by andresesfm** [microsoft/fastlane-plugin-appcenter#106]
Hello. I'm trying to figure out if the following error message is caused by some missing/incorrect parameter that I'm passing or if it is related to some setting on the appcenter plugin. Here is the error:
```
INFO [2019-08-16 15:57:49.19]: Driving the lane 'android upload_appcenter' 🚀
INFO [2019-08-16 15:57:49.19]: ------------------------------
INFO [2019-08-16 15:57:49.19]: --- Step: appcenter_upload ---
INFO [2019-08-16 15:57:49.19]: ------------------------------
INFO [2019-08-16 15:57:49.61]: Starting release upload...
INFO [2019-08-16 15:57:50.02]: Uploading release binary...
INFO [2019-08-16 16:01:49.01]: Binary uploaded
INFO [2019-08-16 16:01:49.71]: Release '5' committed
INFO [2019-08-16 16:01:50.61]: Release 6.0 was successfully updated
ERROR [2019-08-16 16:01:51.45]: Error adding to group 400: {"code"=>"not_supported", "message"=>"Error: Distribution of .aab is not supported for groups/testers"}
ERROR [2019-08-16 16:01:51.45]: Release '5' was not found
```
(Also posted here: https://github.com/microsoft/appcenter/issues/194#issuecomment-522184943)

This is how I call the appcenter_upload method:
```
appcenter_upload(
        api_token: 'MY_TOKEN',
        aab: release_aab,
        destinations: 'Collaborators',
        owner_name: 'my_user_name',
        app_name: 'my-app-android-aab',
        release_notes: load_release_notes || last_git_commit[:message]
      )
```

**Comment by jpeg-ms** [comment]
Hello @andresesfm,
Distribution of `.aab` to groups/testers is not supported. AAB can only be published to Google Play, due to their nature (they can't be directly installed on devices). This is true for the portal, the CLI and this plugin.

**Comment by humblerookie** [comment]
@jpeg-ms I'm not sure this is the best restriction since appcenter serving as a distribution platform would be ideal rather than preventing distribution altogether because users can install. We tend to download the apk and locate the apk on the phone and click install, so the installation experience is anyways independent of distribution dont you think?

**Comment by jpeg-ms** [comment]
Hi @humblerookie,
This is not an artificial restriction from our side. This is simply because an Android App Bundle `.aab` can not be installed directly on a device. In order to install an .aab onto a device, all .apk must be extracted from it using Google's bundletool and then only the exact configuration required by the device should be installed. So the flow is not just "download file and install it" anymore. I know of no plans to duplicate this logic from Google Play.
