### ISSUE TITLE
[Feature] New action to add destinations to an existing release

### ISSUE THREAD

**Issue by jp-andre** [microsoft/fastlane-plugin-appcenter#166]
Similar to the CLI, we probably should have an action to add new destinations to an existing release. This would allow distributing the exact same release to both groups and stores (eg. Collaborators and Alpha), as well as having some more fine-grained options per group, such as asked for in #165.

Creating this Issue here to track popularity. We are not currently working on this.

**Comment by timothy-volvo** [comment]
Hi @jp-andre, I am very interested in this enhancement and may have some time to contribute to its development.

I took a quick look at the source code and there seems to be a method to handle adding a destination in the appcenter_helper.rb. There is just no action exposing the logic. Is this a correct interpretation of the code?

If so, I can try adding an action using the exact parameters at first, it could then be enhanced to pass group names or build versions instead of the ids.

**Comment by jp-andre** [comment]
Hi @timothy-volvo 
Sorry for the late reply. A new action which takes in the release ID and the new destinations would work just fine. PRs are most welcome. When contributing such a PR, please make sure to include complete unit tests.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
