### ISSUE TITLE
Uploads .ipa to Android when both app use the same name.

### ISSUE THREAD

**Issue by cjndubisi** [microsoft/fastlane-plugin-appcenter#213]
hello,

I have these configuration for React Native iOS and Android. When run for ios, the plugin uploads ipa to Android.

 ```
# iOS

    appcenter_upload(
      api_token: ENV['APPCENTER_API_TOKEN'],
      app_name: 'BillSplit',
      notify_testers: true,
      app_os: 'iOS',
      dsym: ENV['FASTLANE_OUTPUT_DIRECTORY'],
      file: ENV['FASTLANE_OUTPUT_DIRECTORY']
    )

#Android

appcenter_upload(
      api_token: ENV['APPCENTER_API_TOKEN'],
      owner_name: 'cjndubisi',
      app_name: 'BillSplit',
      app_platform: 'Java',
      app_os: 'Android',
      notify_testers: true,
      file: './android/app/build/outputs/apk/release/app-release.apk'
    )
```

Rather than changing the name, are there any other solutions?.

**Comment by jp-andre** [comment]
Hi @cjndubisi

The app name that you specify in the Fastfile needs to be the one from the URL. It won't be the same for Android and iOS since in App Center these would be two separate apps.
See [a note on app name](https://github.com/microsoft/fastlane-plugin-appcenter#a-note-on-app-name).

I hope this helps.
