### ISSUE TITLE
Question: Distribute to shared distribution group

### ISSUE THREAD

**Issue by jbrunhuber** [microsoft/fastlane-plugin-appcenter#244]
I would like to distribute an iOS enterprise app to a shared distribution group. It works without problems with a "local" distribution group specifically for an app.

For an organization-wide "shared" distribution group I get the following error: 
`[17:02:44]: Error getting group 403: {"error"=>{"code"=>"Forbidden", "message"=>"You do not have sufficient permission to perform this action on distribution group \"shared-temp-ci\""}}
[17:02:44]: group 'shared-temp-ci' was not found`

This works for my Android colleagues using a Gradle plugin. Is there some other configuration needed to get this working?

**Fastfile**

```ruby
 appcenter_upload(
    api_token: "token",
    owner_name: "Company-Organization",
    owner_type: "organization",
    app_name: "MyApp-iOS-tmp",
    file: "build/binary.ipa",
    destinations: "shared-temp-ci",
    notify_testers: false
 )
```

**Versions**
Fastlane: 2.152.0
AppCenter Plugin: 1.9.0

**Comment by k28gupta** [comment]
Same issue on our iOS app. While Android works just fine.

**Comment by amit3vedi** [comment]
@k28gupta @jbrunhuber i was facing this same issue builds were not distributing to shared group on appcenter for that make sure you are using User token and not App token while pushing build on appcenter

**Comment by jarnove** [comment]
I tried it with both (User & App) tokens, but without any results.
It works for "Collaborators" (because it's by default probably), but when I try to distribute to a specific group, I keep receiving the following error:

`Error getting group 403: {"error"=>{"code"=>"Forbidden", "message"=>"You do not have sufficient permission to perform this action on distribution group \"X\""}}
[21:39:40]: group 'X' was not found`

@jbrunhuber, @k28gupta Were you able to fix this issue?

**Comment by DmitriyKirakosyan** [comment]
Hi @k28gupta , @jbrunhuber , do you still experience this issue?
Have you tried to use User token instead of App token?

**Comment by DmitriyKirakosyan** [comment]
Closing. Let me know if anyone still faces the issue.
