### ISSUE TITLE
Unable to upload Android APK after uploading iOS IPA

### ISSUE THREAD

**Issue by wmcbain** [microsoft/fastlane-plugin-appcenter#28]
I'm working with a React Native project and what we're trying to achieve is building iOS and Android in the same build. However I'm unable to upload the Android APK after uploading the iOS IPA with the following error:

```
ERROR [2018-01-08 11:49:38.79]: Couldn't find dSYM file at path '/Users/vagrant/git/App.app.dSYM.zip'
ERROR [2018-01-08 11:49:38.79]: You passed invalid parameters to 'appcenter_upload'.
ERROR [2018-01-08 11:49:38.79]: Check out the error below and available options by running `fastlane action appcenter_upload`
```

I can't share my entire Fastfile without some editing but in the ios lane we run

```
appcenter_upload(
  api_token: "token",
  owner_name: "Owner",
  app_name: "App",
  ipa: binary_path
)
```

Followed by uploading dsyms after they're downloaded:

```
dsyms = lane_context[SharedValues::DSYM_PATHS]
dsyms.each do |dsym|
  appcenter_upload(
    api_token: "token",
    owner_name: "Owner",
    app_name: "App",
    upload_dsym_only: true,
    dsym: dsym
  )
end
```

After this completes we build Android and in that lane run:

```
appcenter_upload(
  api_token: "Token",
  owner_name: "Owner",
  app_name: "App",
  apk: "./android/app/build/outputs/apk/app-releaseStaging.apk"
)
```

`:APPCENTER_BUILD_INFORMATION` at the point of Android is set to the iOS project unsure if it helps, but thought that it might. Thanks!

**Comment by evkhramkov** [comment]
@wmcbain does it work if you build and upload only Android?

**Comment by wmcbain** [comment]
@evkhramkov It does work when Android is run on it's own. Do I need to clear env variables in between steps?

**Comment by richardmtsr** [comment]
@evkhramkov Is there an update on this? I'm having the same issue. Really want to be able to run both builds together but at the moment we are restricted.

**Comment by amalshah71** [comment]
Any update on this ?

If i even do only Android, it says :: "couldn't find build path..."

**Comment by evkhramkov** [comment]
@richardmtsr @amalshah71 @wmcbain sorry for so late response.
Is this still an issue for you?

As you can see on [travis build logs](https://travis-ci.org/Microsoft/fastlane-plugin-appcenter), we are running all possible action variations which includes uploading dsym files for ios, and uploading apk after (Check [lane test in `fastlane/Fastfile`](https://github.com/Microsoft/fastlane-plugin-appcenter/blob/master/fastlane/Fastfile#L32)) and we don't have any issues

**Comment by krimsonkla** [comment]
I ran into this same thing today and dug in a bit. I believe the problem is not in having uploaded an iOS build but in having built an iOS app. If you have ran any build_ios_app type actions you will have a lake context value in `Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]` The appcenter_upload_action then uses this lane context as a default value for the ipa parameter.

So, even though you may have specified an apk at that point you will have unintentionally specified both an apk and an ipa in the action params. 

Based on the code at https://github.com/microsoft/fastlane-plugin-appcenter/blob/master/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L119 if an ipa and an apk are both specified ipa will win and become the upload file.

**Comment by zanizrules** [comment]
I ran into an issue where both android and ios were failing to upload when my process was building both then uploading android followed by iOS. After reading your comment @krimsonkla I added `Actions.lane_context[SharedValues::IPA_OUTPUT_PATH] = nil` before calling the upload actions. After doing so it worked fine.

**Comment by jpeg-ms** [comment]
The SharedValues are set by fastlane, not by this plugin. Maybe an alternative solution would be to specify the path to the .ipa and .apk (or .aab) files explicitly in the appcenter_upload action? You can use the generic "file:" field.

**Comment by krimsonkla** [comment]
The problem with this suggestion is the use of lane_context in the default values for fastlane action options. Even if we do specify the app using the generic :file option there are conditions where it will not be used.

Example: If I have built an iOS build, fastlane will automatically set the lane context 'Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]' which appcenter is then using as the default value for the :ipa option. Once this is set it will then become the default "winner" for any attempted upload due to the code listed here. In fact :file is the last possible option and will almost never actually be used. https://github.com/microsoft/fastlane-plugin-appcenter/blob/71bb20555f88f5ab0bb846f669bc0337809ecccc/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb#L134

This really seems like a defect, not an enhancement.

**Comment by krimsonkla** [comment]
PR #156 has resolved this issue for me. Thanks!

**Comment by jpeg-ms** [comment]
Fantastic!
