### ISSUE TITLE
Can't release to destination groups other than "Collaborators" with App API token

### ISSUE THREAD

**Issue by dockay** [microsoft/fastlane-plugin-appcenter#306]
We are using fastlane 2.209.1 and are using fastlane to upload our ipa to our AppCenter organization, to a specific app.

We generated an `App API token` with _full access_. Uploading the binary to appcenter has no issues, though adding the specified destination group results in these errors:

> Error adding app to distribution group 403: {"message"=>"A app API token cannot be used to make requests to this endpoint. Please use a user API token.", "statusCode"=>403, "code"=>"Forbidden"}

> Error getting group 403: {"error"=>{"code"=>"Forbidden", "message"=>"You do not have sufficient permission to perform this action on distribution group \"App Team Tester\""}}
group 'App Team Tester' was not found

our fastlane call looks like this:
```ruby
appcenter_upload(
      api_token: "-secret-",
      owner_name: "owner",
      owner_type: "organization",
      app_name: "App-Test",
      destinations: "Collaborators, App Team Tester",
      file: ENV["FSTLN_IPA_PATH"],
      notify_testers: false,
      release_notes: ENV["FSTLN_DEPLOY_APPCENTER_RELEASE_NOTES"]
    )
```
The only solution seems to generate a `User API Token` with _full access_ but that undermines security issues as this needs to be generated by a real person. If this person leaves etc. the token will be invalidated, that seems absolutely not practicable. As the Account needs to be a real account (with 2FA, github/facebook/google etc.) there is no way to create a technical only account for this.

**Comment by DmitriyKirakosyan** [comment]
Hi @dockay , is it a shared distribution group (organization level)? In that case you will need a user api token. See [Types of Tokens](https://docs.microsoft.com/en-us/appcenter/api-docs/#section02).

**Comment by aleksandr-dorofeev** [comment]
Hi @dockay
We haven't heard from you in a while so I'm closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by DelcoigneYves** [comment]
Can we reopen this issue? We have encountered the same issue, but I would like to challenge the proposed solution (for the case where the distribution group is on the organizational level).

An app API token is safer to use, and it should be possible to use it, as the AppCenter API allows it as well.
A colleague investigated this, and found that the root cause of the error, is because the AppCenter API does not allow the retrieval of a shared group's details (and thus groupId) with an app-specific API token. However, it is perfectly possible to assign a release to a shared distribution group with an app-specific API token as long as you have the groupId. 

So a possible improvement to allow this, would be to add another property to the `appcenter_upload` lane, next to the `destinations` property, to allow adding a list of group IDs instead of group names.

**Comment by DmitriyKirakosyan** [comment]
@DelcoigneYves , thank you for the contribution! Your PR is merged. I'll update you once the fix is released.

**Comment by Vyazovoy** [comment]
Would it be possible to release this fix. I'm experiencing the same limitation.

**Comment by AnatolyPristensky** [comment]
@Vyazovoy, the new release with this fix is available.
