### ISSUE TITLE
Upload to organisation- apps not supported

### ISSUE THREAD

**Issue by balchander** [Microsoft/fastlane-plugin-appcenter#46]
Unable to upload the app to the organization-app.

I don't see any information related to the organisation in the documentation or in the code.
upload url I see in the code, `req.url("/v0.1/apps/#{owner_name}/#{app_name}/release_uploads/#{upload_id}")`

Need the support to upload the .ipa to the organisaiton-app.

**Comment by vgrigorjeva** [comment]
@balchander have you managed to do this?

**Comment by balchander** [comment]
@vgrigorjeva Yes.
If your app URL is `"https://appcenter.ms/orgs/<org-name>/apps/<app-name>"`

`appcenter_upload(
      api_token: <api-token>,
      owner_name: <org-name>,
      app_name: <app-name>,
      ipa: "./App.ipa",
      release_notes: <notes>,
    )`

**Comment by vgrigorjeva** [comment]
Thank you, @balchander , but this didn't work for me. I found another solution so far.

**Comment by dlarrain** [comment]
How do you managed to do this @vgrigorjeva

**Comment by vgrigorjeva** [comment]
@dlarrain , I forked this repository (https://github.com/vgrigorjeva/fastlane-plugin-appcenter) where I changed the upload path. in `Pluginfile` instead of `gem 'fastlane-plugin-appcenter'` I used `gem 'fastlane-plugin-appcenter', github: "vgrigorjeva/fastlane-plugin-appcenter", ref: "toOrg"`, so I could do my first upload to organization app. After @balchander comment I tried to make another upload, but without fork and it worked..

**Comment by filipkowicz** [comment]
current microsoft `master` has support orgs already

**Comment by evkhramkov** [comment]
not yet, PR is still open #75

**Comment by DennisPan** [comment]
@evkhramkov To clarify, upload to organization is current supported, but automatically creating an app under organization is not. Is that correct?

**Comment by evkhramkov** [comment]
@DennisPan yes, you're right. We have a PR #75 for auto creation but it is still open with the question about api design (should it have explicit `isOrg` parameter or not)
