### ISSUE TITLE
No symbols after upload (iOS)

### ISSUE THREAD

**Issue by Bobrovsky** [Microsoft/fastlane-plugin-appcenter#51]
Hello,

I am using latest fastlane (2.114) and appcenter plugin. During the build I see this in the log:
```
Binary uploaded
..
dSYM uploaded
```
I do not know how to verify if dSYM is actually uploaded to App Center, but in the Hockeyapp I do see the build, but do not see dSYM. Instead I see Symbols none.

Why? How can I fix this?

I use plugin like this:

```
appcenter_upload(
    api_token: "my_token",
    owner_name: "my_company",
    group: "Collaborators,some-other-group",
    app_name: "app-name",
    ipa: "ipa-path",
    dsym: "dsym-path"
)
```

**Comment by wyzzy** [comment]
I'm seeing a similar problem, however I have done a couple of extra things:

- Modified the Xcode build script to generate a source map file at bundling time (added `export EXTRA_PACKAGER_ARGS="--sourcemap-output ios/build/index.ios.map"` just before the bundling command - based on https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication)
- Created a lane to unzip the app's dSYM.zip file, and create a new zip with the index.ios.map and dSYM file
- Included the new dSYM.zip in the appCenter_upload.

I have two problems:
- App Center isn't recognising my dSYM zip as being valid (contains no symbols)
- If I user Finder to create a new archive with the unzipped dSYM and index.ios.map in, I can upload that through the App Center diagnostics page. It says my reports are now symbolicated, but the JS side is not complete.

My JS stack trace is only partially symbolicated though. I suspect that's because my app is actually written in TypeScript. Does anybody have any tips on how to generate a source map for the bundled js when all the js source is actually TypeScript?

A sample of the raw crash report in App Center is below:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: o: o: Attempt to retrieve transactions before the account has been set

This error is located at:
    in Connect(n)
    in v
    in RCTView
    in f
    in RCTView
    in f
    in S
    in n
    in P
    in RCTView
    in n
    in RCTView
    in f
    in S
    in y
    in L
    in RCTView
    in h
    in C
    in k
    in v
    in v
    in RCTView
    in RCTView
    in l
    in RCTView
    in n
    in RCTView
    in n
    in _
    in k
    in v
    in l
    in k
    in v
    in l
    in k
    in k
    in RCTView
    in l
    in Connect(l)
    in c
    in s
    in n
    in RCTView
    in RCTView
    in Unknown
    in RCTView
    in c
```

**Comment by derpixeldan** [comment]
There's currently no way to review the list of uploaded symbols. I would encourage you to create a feature request in our [public repo](https://github.com/microsoft/appcenter).

FYI @winnieli1208

**Comment by Bobrovsky** [comment]
@derpixeldan I was talking about reviewing symbols in **Hockeyapp**. 

When I upload a build with symbols to appcenter I do see the build in the Hockeyapp, but I do not see the symbols **there**.
